[settings]
experimental = true
python_venv_auto_create = false

[env]
GIT_EDITOR = "nvim"
PIP_REQUIRE_VIRTUALENV = 'true'
RIPGREP_CONFIG_PATH = '{{env.HOME}}/.config/rg/ripgreprc'

[tools]
fd = 'latest'
fzf = 'latest'
ripgrep = 'latest'
yamllint = 'latest'
# npm stuff
"npm:@vtsls/language-server" = "latest"
"npm:eslint" = "latest"
"npm:eslint_d" = "latest"
"npm:prettier" = "latest"
"npm:@fsouza/prettierd" = "latest"
# runtimes (needs to be last)
bun = 'latest'
go = ['1.22', '1.21']
node = "20"
python = ['latest', 'sub-0.1:latest', 'sub-0.2:latest', 'sub-0.3:latest']
neovim = "nightly"
