[settings]
experimental = true

[env]
GIT_EDITOR = "nvim"
PIP_REQUIRE_VIRTUALENV = 'true'
RIPGREP_CONFIG_PATH = '{{env.HOME}}/.config/rg/ripgreprc'

[tools]
fzf = 'latest'
yamllint = 'latest'
zoxide = 'latest'
# npm stuff
"npm:@vtsls/language-server" = "latest"
"npm:eslint" = "latest"
"npm:eslint_d" = "latest"
"npm:prettier" = "latest"
"npm:@fsouza/prettierd" = "latest"
# runtimes (needs to be last)
bun = 'latest'
go = 'latest'
python = "3.14"
neovim = "nightly"
node = "24"
